version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./devops/src/docker/Dockerfile
    ports:
    - "3000:3000"
  server:
    - db
    build:
      context: ./server
      dockerfile: ./devops/src/docker/api_dockerfile
    ports:
    - "80:5001"
    volumes:
    - ./server/
  db:
    image: mdillon/postgis:10-alpine
    volumes:
    - /data/gearmap_db:/var/lib/postgresql/data
    ports:
    - 5432:5432
       