version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./devops/src/docker/Dockerfile
    volumes:
    - ./client:/app
    ports:
    - "3001:3000"
    volumes:
    - ./client:/app
  server:
    depends_on:
    - db
    build:
      context: ./server
      dockerfile: ./devops/src/docker/api_dockerfile
    ports:
    - "5001:5000"
    volumes:
    - ./server/common:/gearmap/common
    - ./server/devops:/gearmap/devops
    - ./server/src:/gearmap/src
  db:
    image: postgis/postgis:11-2.5-alpine
    volumes:
    - /data/gearmap_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${GEARMAP_DBPASS:-postgres}
    ports:
    - 5431:5432
       