version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./devops/src/docker/Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./client:/app
  server:
    depends_on:
    - db
    build:
      context: ./server
      dockerfile: ./devops/src/docker/api_dockerfile
    ports:
    - "80:5001"
    env_file:
      - .env
    #environment:
    #  - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - ./server/common:/gearmap/common
    - ./server/devops:/gearmap/devops
    - ./server/src:/gearmap/src
  db:
    image: mdillon/postgis:10-alpine
    volumes:
    - /data/gearmap_db:/var/lib/postgresql/data
    ports:
    - 5432:5432
       