version: "3"
services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: ./devops/src/docker/Dockerfile
  #   volumes:
  #   - ./client:/app
  #   ports:
  #   - "3001:3000"
  server:
    depends_on:
    - db
    build:
      context: ./server
      dockerfile: ./devops/src/docker/Dockerfile
    environment:
      - GEARMAP_DBHOST=${GEARMAP_DBHOST:-db}
      - GEARMAP_DBPORT=${GEARMAP_DBPORT:-5432}
      - GEARMAP_DBNAME=${GEARMAP_DBNAME:-postgres}
      - GEARMAP_DBPASS=${GEARMAP_DBPASS:-postgres}
      - GEARMAP_DBUSER=${GEARMAP_DBUSER:-postgres}
      - GEARMAP_DBSCHEMA=${GEARMAP_DBSCHEMA:-gearmap}
    ports:
    - "5001:5001"
    volumes:
    - ./server/common:/gearmap/common
    - ./server/devops:/gearmap/devops
    - ./server/src:/gearmap/src
  db:
    image: postgis/postgis:11-2.5-alpine
    volumes:
    - ./gearmap_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${GEARMAP_DBPASS:-postgres}
    ports:
    - 5431:5432
       
